name: 部署到生产环境

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 安装前端依赖
      run: npm ci
      
    - name: 构建前端
      run: npm run build
      
    - name: 安装后端依赖
      run: |
        cd backend
        npm ci
        
    - name: 运行测试
      run: |
        npm test
        cd backend
        npm test
        
    - name: 部署到 Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./
        
  backend-deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 安装后端依赖
      run: |
        cd backend
        npm ci
        
    - name: 构建后端镜像
      run: |
        cd backend
        docker build -t newgold-backend .
        
    - name: 部署后端
      run: |
        echo "后端部署配置待完善"
        # 这里可以配置部署到云服务器或容器平台